### PR TITLE
Update Devices

### PR DESCRIPTION
**Pull request by Bitti09**

### CODE REVIEW

**Comment by r-matlock** [comment]
@Bitti09 are you building the Mi 3 on Amy's server?

**Comment by AmyClaraRose** [comment]
Please include device code name please only reason g3 doesn't is because of how many codenames it has

**Comment by vbajs** [comment]
@Bitti09 you can add the codename of the device you are maintaning by :-
1. Go to your fork of this repo
2. Commit that change where you add the codename of the device
And that's it
It will soon appear on the Pull request, so no need of another pull request for that

**Comment by Bitti09** [comment]
Added

**Comment by vbajs** [comment]
Good,
Now either @minidude2012 or @xX-Yoshi-Xx can merge this

**Pull request closed without merging**
